spring:
  mvc:
    static-path-pattern: /api/static/**
  config:
    activate:
      on-profile:
        - dev

  datasource:
    url: jdbc:mysql://db-dev:3306/attendanceDb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true



logging:
  level:
    com.alphastarav.identity: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security.ldap: TRACE

app:
  security:
    username: johndoe
    password: password
  utils:
    time-in-seconds-to-unlock-user: ${TIME_IN_SECONDS_TO_AUTO_UNLOCK_USER_ACCOUNT:20}
    trusted-sender: ${MAIL_TRUSTED_SENDER:admin@dev.com}
    time_zone: UTC
    tokenUtils:
      - type: OTP
        expiryInMs: 300000
        perUserUnique: false
        limit: 3
  jwt:
    secret: ${JWT_SECRET:HlBPWkL3PkzTnMyKbW1FOkmOcdmby7GLQ38iiYP/XYH7nMl57DhLwQN7F6JWfTpzk14ryv5I5Iavz6VktEHHQw==}
    algorithm: HS256
    expiry-in-ms: 3600000
    expiry-in-ms-refresh-token: 86400000
  cors:
    allowed-methods: [ GET, POST, PUT, DELETE, PATCH ]
    allowed-headers: [ "*" ]
    allowed-origins: [ "*" ]
    exposed-headers: [ ]
    credentials: false
