spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  config:
    activate:
      on-profile:
        - dev

  datasource:
    url: jdbc:mysql://localhost:3306/attendanceDb?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:3020}
    protocol: ${MAIL_PROTOCOL:smtp}
    password: SG.V3_H-eStSluH0juw35iuFg.DGAWtIzzedDVoZb13XVVyhvoqbrNNCJdKW5YIVbx
    username: apikey
    TRUSTED_SENDER: marketing@alphastar.com
    properties:
      mail:
        smtps:
          auth: true
          starttls:
            enable: true
logging:
  level:
    com.alphastarav.identity: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security.ldap: TRACE

app:
  active-directory.enabled: false
  security:
    username: johndoe
    password: password
  utils:
    time-in-seconds-to-unlock-user: ${TIME_IN_SECONDS_TO_AUTO_UNLOCK_USER_ACCOUNT:20}
    trusted-sender: ${MAIL_TRUSTED_SENDER:admin@dev.com}
    tokenUtils:
      - type: OTP
        expiryInMs: 300000
        perUserUnique: false
        limit: 3
  jwt.secret:  ${JWT_SECRET:HlBPWkL3PkzTnMyKbW1FOkmOcdmby7GLQ38iiYP/XYH7nMl57DhLwQN7F6JWfTpzk14ryv5I5Iavz6VktEHHQw==}


